//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr1_10._09
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoServeceEntities : DbContext
    {
        public AutoServeceEntities()
            : base("name=AutoServeceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Parts> Parts { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<PlayersParts> PlayersParts { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
