//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr1_10._09
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayersParts
    {
        public int PlayerID { get; set; }
        public int PartsID { get; set; }
        public int Count { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Parts Parts { get; set; }
    }
}
